### ISSUE TITLE
Add SearchBuilder

### ISSUE THREAD

**Issue by rickmedlin** [fiduswriter/Simple-DataTables#180]
As you may know, the jquery DataTables has a SearchBuilder property that allows the user to set conditions on multiple columns. Are there any plans to add that to this library?

https://datatables.net/extensions/searchbuilder/examples/initialisation/simple.html

**Comment by johanneswilm** [comment]
I think they need that because they are in the jQuery-world. In modern ES2022, one can just copy, adjust and paste the general search functionality to do what one wants to. I cannot really see what good the search builder would do.

https://github.com/fiduswriter/Simple-DataTables/blob/main/src/datatable.js#L908-L971
