### ISSUE TITLE
Style problems

### ISSUE THREAD

**Issue by Pasqualeperf** [fiduswriter/simple-datatables#217]
All styles are losts without no errors in console. (Installed from CDN)
` <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>`
`<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">`

```
   const datatablesHome = document.querySelector('#datatablesHome');
    if (datatablesHome) {
        new simpleDatatables.DataTable(datatablesHome);
    }

    const datatablesAllContracts = document.querySelector('#datatablesAllContracts');
    if (datatablesAllContracts) {
        new simpleDatatables.DataTable(datatablesAllContracts);
    }
```

**Comment by johanneswilm** [comment]
Hey @Pasqualeperf - please look at the front page of the repository. Let me know if you have further questions.

**Comment by cdru** [comment]
Even following the front page, things aren't working quite as indicated at least when using the jsdelivr.net CDN.

The code block under the note for the CDN still shows examples using @latest for the version, despite the note. Using the example url, the js file loads 6.0.0-5, but for the css file it still loads what appears to be an older 5.x version with the mixed case class names. In either case, for those of us who like to live dangerously, it's not loading the "latest" version for either file.

If @5 is specified as the note indicates for the major version, 5.0.3 loads. However if @6 is used, an error is returned for both the js and css files. The full version, for example @6.0.0-11, needs to be used to pull the latest in the 6.x branch.

Unpkg.com WAS throwing errors when any of the 6.x releases I tried just a bit ago, however it appears that might have been a transitory issue. It appears to be working as expected for the full version number and @latest. Specifying only @6 doesn't work however. 

I also noticed that https://unpkg.com/simple-datatables@latest redirects to the 6.0.0-12 version, when the latest in github is 6.0.0-11 as of this comment being submitted.

**Comment by johanneswilm** [comment]
Hey @cdru 

> Using the example url, the js file loads 6.0.0-5

Where do you see that example URL?

> The code block under the note for the CDN still shows examples using @latest for the version, despite the note. 

That is on purpose. It is correct to you @latest for development purposes. It's only when you ship to production that you will want to specify version.

> However if @6 is used, an error is returned for both the js and css files. The full version, for example @6.0.0-11, needs to be used to pull the latest in the 6.x branch.
> ...
> Specifying only @6 doesn't work however.

That is likely because version 6 has not yet been released. In the naming scheme used by npm, 6.0.0-12 is a prerelease of version 6. I will release version 6 once neither me nor others here can find bugs in it.

I am quite surprised that some of the CDN services serve a release candidate as a @latest release.

> I also noticed that https://unpkg.com/simple-datatables@latest redirects to the 6.0.0-12 version, when the latest in github is 6.0.0-11 as of this comment being submitted.

Yes, given that there are so many versions per day right now, I am not always pushing everything to github first.

**Comment by johanneswilm** [comment]
> > Using the example url, the js file loads 6.0.0-5
>
> Where do you see that example URL?

Ah you mean by jsdelivr? Yes, I see 6.0.0-8 here (southern Sweden). It's probably a caching issue with them. There was a CSS issue earlier, but it was solved before 6.0.0-8 was released. And it's only a release candidate, so I was a bit surprised that quite a few people here were using it in production. Therefore the note.

**Comment by cdru** [comment]
> > > Using the example url, the js file loads 6.0.0-5
> > 
> > 
> > Where do you see that example URL?
> 
> Ah you mean by jsdelivr? Yes, I see 6.0.0-8 here (southern Sweden).

Yes, with jsdelivr. I'm in Indiana, United States and for me, https://cdn.jsdelivr.net/npm/simple-datatables@latest showed a header comment indicating the original file was /npm/simple-datatables@6.0.0-5/dist/umd/simple-datatables.js.

> It's probably a caching issue with them.

I figured it was either a caching issue or just still propagating out and taking a bit longer for whatever reason.

> And it's only a release candidate

Since it was a pre-release, yeah it's all on me not noticing it. I'm more accustomed for pre-releases to include -alpha, -beta, or -rc as part of the version number. I didn't even realize that the official semver specs don't require anything specific like that. That also explain why `@6` doesn't work yet, since 6.0.0 isn't officially released.

> I was a bit surprised that quite a few people here were using it in production.

I don't think that it's unreasonable to expect `@latest` on the main branch to point to the latest stable release and not the bleeding edge latest. I came across a [comment from a different project](https://github.com/raineorshine/npm-check-updates/issues/368#issuecomment-308748703) that states similar. 

I admit however that I'm not familiar with what happens behind the scenes when a new [pre]release version is available, building the package to be published, deploying to the various CDNs, etc. Perhaps it's more complicated that what I realize.

> Therefore the note.

Being a dense developer who doesn't RTM first, I still found it confusing even after reading the note. The upgrading section talks about upgrading from v5 to v6, with no mention that v6 is still a RC. And then the note talks about specifying the major version but `@6` doesn't work quite yet. 

Even if `@latest` can't/won't be fixed to not include pre-release versions, perhaps the 2 lines of HTML for the CDN could be reformatted to better indicate stable/RC versions until v6 actually is released. For example:

```
Latest Stable (v5.x):
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@5/dist/style.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@5" type="text/javascript"></script>

Latest Release Candidate (v6.x):
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@6.0.0-12/dist/style.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@6.0.0-12" type="text/javascript"></script>

Bleeding Edge Latest:
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
```

Same thing applies to npm and yarn sections as they default to the `@latest` branches and install the RC version currently as well.

**Comment by Rpgdudester** [comment]
> > > > Using the example url, the js file loads 6.0.0-5
> > > 
> > > 
> > > Where do you see that example URL?
> > 
> > 
> > Ah you mean by jsdelivr? Yes, I see 6.0.0-8 here (southern Sweden).
> 
> Yes, with jsdelivr. I'm in Indiana, United States and for me, https://cdn.jsdelivr.net/npm/simple-datatables@latest showed a header comment indicating the original file was /npm/simple-datatables@6.0.0-5/dist/umd/simple-datatables.js.
> 
> > It's probably a caching issue with them.
> 
> I figured it was either a caching issue or just still propagating out and taking a bit longer for whatever reason.
> 
> > And it's only a release candidate
> 
> Since it was a pre-release, yeah it's all on me not noticing it. I'm more accustomed for pre-releases to include -alpha, -beta, or -rc as part of the version number. I didn't even realize that the official semver specs don't require anything specific like that. That also explain why `@6` doesn't work yet, since 6.0.0 isn't officially released.
> 
> > I was a bit surprised that quite a few people here were using it in production.
> 
> I don't think that it's unreasonable to expect `@latest` on the main branch to point to the latest stable release and not the bleeding edge latest. I came across a [comment from a different project](https://github.com/raineorshine/npm-check-updates/issues/368#issuecomment-308748703) that states similar.
> 
> I admit however that I'm not familiar with what happens behind the scenes when a new [pre]release version is available, building the package to be published, deploying to the various CDNs, etc. Perhaps it's more complicated that what I realize.
> 
> > Therefore the note.
> 
> Being a dense developer who doesn't RTM first, I still found it confusing even after reading the note. The upgrading section talks about upgrading from v5 to v6, with no mention that v6 is still a RC. And then the note talks about specifying the major version but `@6` doesn't work quite yet.
> 
> Even if `@latest` can't/won't be fixed to not include pre-release versions, perhaps the 2 lines of HTML for the CDN could be reformatted to better indicate stable/RC versions until v6 actually is released. For example:
> 
> ```
> Latest Stable (v5.x):
> <link href="https://cdn.jsdelivr.net/npm/simple-datatables@5/dist/style.css" rel="stylesheet" type="text/css">
> <script src="https://cdn.jsdelivr.net/npm/simple-datatables@5" type="text/javascript"></script>
> 
> Latest Release Candidate (v6.x):
> <link href="https://cdn.jsdelivr.net/npm/simple-datatables@6.0.0-12/dist/style.css" rel="stylesheet" type="text/css">
> <script src="https://cdn.jsdelivr.net/npm/simple-datatables@6.0.0-12" type="text/javascript"></script>
> 
> Bleeding Edge Latest:
> <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
> <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
> ```
> 
> Same thing applies to npm and yarn sections as they default to the `@latest` branches and install the RC version currently as well.

Thank you for posting those CDN links, I just spent 20 minutes chasing my tail because my tables just started failing to load the styles (I was using the @latest to load as well since that is what was on their main page). I flipped it back to @5 and it worked out perfectly. and my tables came back.


So thank you! and thank you to all the people who wrote this great software!

**Comment by johanneswilm** [comment]
>> And it's only a release candidate
>
> Since it was a pre-release, yeah it's all on me not noticing it. I'm more accustomed for pre-releases to include -alpha, -beta, or -rc as part of the version number. I didn't even realize that the official semver specs don't require anything specific like that. That also explain why @6 doesn't work yet, since 6.0.0 isn't officially released.

The way I created `6.0.0-0` was with the command `npm version premajor && npm publish`. The following releases were created with `npm version prerelease && npm publish`. Yes, there is a command line flag to add "rc" to the name, but the default is to leave it off. I was just as confused as you about this, but given that the version numbers were created from the official tools, I assumed that it was just me who was out of date.

> I don't think that it's unreasonable to expect `@latest` on the main branch to point to the latest stable release and not the bleeding edge latest. I came across a [comment from a different project](https://github.com/raineorshine/npm-check-updates/issues/368#issuecomment-308748703) that states similar.

I agree. But I'm not in charge of npm and/or jsdelivr. At any rate, even if done that way, your project would have broken once the official version 6 has been released as there are many breaking changes. One will always need to lock down to a version to avoid that.

**Comment by johanneswilm** [comment]
> Being a dense developer who doesn't RTM first, I still found it confusing even after reading the note. The upgrading section talks about upgrading from v5 to v6, with no mention that v6 is still a RC. And then the note talks about specifying the major version but @6 doesn't work quite yet.

The github wiki only allows us to show one version AFAIK. It's quite a lot of work to update the manual and so there will be times when it is ahead of where you are.

Now that we have all learned that "6.0.0-0" means "prerelease of "6.0.0" according to semver, I think there is not much to complain about. At least not to me. But send your frustration to jsdelivr and/or npm.

**Comment by johanneswilm** [comment]
@cdru It gives that same information in the official jsdelivr documentation:

> Omit the version completely or use "latest" to load the latest one (not recommended for production usage):
> ...
> Requesting the latest version (as opposed to "latest major" or "latest minor") is dangerous because major versions usually come with breaking changes. Only do this if you really know what you are doing.

https://www.jsdelivr.com/features

The only reason I repeat in the README of this project is that apparently there are many web developers who are not aware of this. And I guess it makes sense that it is the way it is. Who would one think that it would be possible to just use whatever is the latest release and not ever have it break? That's the entire point of major version numbers, isn't it? It would probably be a good idea for them to offer a way of specific "latest production release"

As for prereleases not carrying "rc" by default - apparently there is a history behind this. They first rejected adding an option to add letters to prereleases altogether [1]. This has since been made possible, but only as an addition, not as a default choice for prereleases. 

All the above being said, version 6 should generally be more stable than version 5. And I think that it will likely be released within a few hours and then you would have had the same problem with the @latest tag.

[1] https://github.com/npm/npm/pull/12936#issuecomment-248153743
