### ISSUE TITLE
[v6.0.3] Classes in table element gets rewritten

### ISSUE THREAD

**Issue by tanishqv** [fiduswriter/simple-datatables#232]
The classes added to the `table` gets replaced with the ones that the scripts add.

I tried adding bootstrap 5.2.x classes, `table`, `table-striped`, `table-hover` to a table but they get replaced with `datatable-table`.

This has been observed in `latest` (v6.0.3) and v6.0.0-0 onwards but working fine in v5.0.3

Please check screenshots

**Browser used:** Brave
**Version:** v1.47.171
**OS arch:** 64-bit
**OS:** Windows 10

_v5.0.3_
![v5 0 3](https://user-images.githubusercontent.com/40364058/212843164-6dea043f-3f9f-403b-997f-cfdd7ec9e19a.png)

_v6.0.3_ or _latest_
![v6 0 3](https://user-images.githubusercontent.com/40364058/212843266-5af75bfa-8239-48f3-b27b-ef86d1bde516.png)

**Comment by johanneswilm** [comment]
Hey @tanishqv ,
yes, this is intentional. I have added a few more explanations in https://fiduswriter.github.io/simple-datatables/documentation/Upgrading and reordered the existing instructions to make it clearer.

You can  add additional classnames to rows and cells using `rowRender`. You can currently not add extra classes to the header, but I'm wondering whether maybe we need a `headerRender` option as well. 

Would you ned to add classes to the header as well, or would it be enough being able to exchange the class names used in the header as you can already do?

**Comment by tanishqv** [comment]
I was able to add other classes in v6.0.3 to the table using the following script by following the documentation for [classes](https://fiduswriter.github.io/simple-datatables/documentation/classes).

```
document.addEventListener("DOMContentLoaded", function(){
        const dataTable = new simpleDatatables.DataTable("#all-res", {
            classes: {
                table: "datatable-table table table-striped table-hover"
            },
        })
    })
```

![image](https://user-images.githubusercontent.com/40364058/212878229-f9348de8-828c-4401-88f7-221af8e2c6db.png)


Thanks for the pointer.

**Comment by johanneswilm** [comment]
Hey,
well, it's really just meant for a single class name. For some of the options you may be able to squeeze multiple in there, but for others it will surely crash the system.
