### ISSUE TITLE
Number Sorting Alphabetically Instead of Largest to Smallest 

### ISSUE THREAD

**Issue by thorntonedgar** [fiduswriter/simple-datatables#242]
I just upgraded to 6.0.7 and numbers aren't sorting correctly for me now. 
![image](https://user-images.githubusercontent.com/22010936/213577576-22a1a23c-ca5a-4976-a17a-df2a3c1c8db7.png)

This is probably an issue with my configuration - but I'm also seeing it in the demo: 
![image](https://user-images.githubusercontent.com/22010936/213577995-07600caf-e90c-463f-ae2a-68e51165b440.png)
https://fiduswriter.github.io/simple-datatables/demos/1-simple/

Do i need to specify the type? 

Edit - rolled back to @5 and it's working just fine there. Not sure where the issue is, i'll dive in to see if i can find

**Comment by johanneswilm** [comment]
Hey @thorntonedgar ,
how are you adding the data? In the case of demo 1, it is just reading strings from HTML (such as "14%") so it's ordering it as a string. Sorting in @5 was quite broken, but it's possible that strings with numbers were treated in a special way there. I can investigate. Did you specify a type?

**Comment by johanneswilm** [comment]
I converted demo5 to use numbers rather than strings and then sorting is working: https://fiduswriter.github.io/simple-datatables/demos/5-column-manipulation/

**Comment by thorntonedgar** [comment]
> Hey @thorntonedgar ,
> how are you adding the data? In the case of demo 1, it is just reading strings from HTML (such as "14%") so it's ordering it as a string. Sorting in @5 was quite broken, but it's possible that strings with numbers were treated in a special way there. I can investigate. Did you specify a type?


Just reading the strings from html.

I did not specify a type, in the documentation it's not clear now to specify a type (other than dates).

**Comment by johanneswilm** [comment]
Yeah, "date" is the only type one can specify, but I can see that we should probably also have a type "number" for this exact purpose.

In version 5 it simply removes all percentage signs, Dollar signs, commas and spaces and then tries whether the remaining string contain a number [1] and if so uses that number to sort. So that happens to work in your case but wouldn't work for anyone with any other currency, so that's not something we should go back to, I think.

I think what I'll do is add a type "number" and if that is specified, it will simply remove all non-numeric characters to find the order number upon import and then sort according to that number. 

How does that sound?

[1] https://github.com/fiduswriter/simple-datatables/blob/ad5eaa58ecfc7ecdcaad8a8361c832a68b782130/src/columns.js#L372

**Comment by thorntonedgar** [comment]
That sounds perfect. Thanks for finding a solution so quickly.

**Comment by johanneswilm** [comment]
This has been fixed in version `7.0.0-rc.0`. Please check out so we can get a release soon.
