### ISSUE TITLE
HTML Select Field - Cannot Set Default/Selected Value

### ISSUE THREAD

**Issue by rootlo0p** [fiduswriter/simple-datatables#247]
When using a dropdown menu in a field, the JavaScript or styling prevents the default value from being shown/selected, defaulting to show the first option value instead.

For example, the field below contains the `selected="selected"` attribute for option value `3`, meaning that the browser should render the dropdown menu with option `3` shown/selected by upon loading the page.

```html
<th>
    <select name="field_test" autocomplete="off">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3" selected="selected">3</option>
        <option value="4">4</option>
    </select>
</th>
```

**Expected Behavior**: Upon loading the page, the browser should render the HTML dropdown menu to show/select the option value containing the `selected` attribute.

**Observed Behavior**: In all browsers, the HTML ultimately renders with option value `1` (the first value listed) shown/selected rather than the option value containing the `selected` attribute. The behavior returns to the expected behavior after removing the ` id="datatablesSimple"` attribute from the parent table element.

After moderate troubleshooting, I was unable to narrow down the cause.

**Comment by johanneswilm** [comment]
@rootlo0p Which version of simple-data-tables? I tried on both 6.0.8 and 7.0.0-rc.1 in a header cell as well as a body cell in both Chrome and Firefox and in all cases it did show correctly with "3" selected.

**Comment by johanneswilm** [comment]
Cannot reproduce.

**Comment by rootlo0p** [comment]
Version 6. I now realize that the elements are set as expected on page load, for first-page results; however, it is the search-and-sort features that cause them to set back to the first option value, away from the `selected="selected"` default value.

If I have a row containing a field on the first page with the string "Alphabet," here is what happens to the `field_test` option values as I type into the search feature:

On page load, for a first-page result: `field_test` shows `3` for a row containing `Alphabet`
Search `A`: `field_test` shows `3`
Search `Al`: `field_test` shows `3`
Search `Alp`: `field_test` shows `1`
Search `Alph` (and beyond): `field_test` shows `1`
Backspace (now search is `Al` again): `field_test` shows `3`
Backspace (now search is `A` again): `field_test` shows `3`
Backspace (now search is now empty): `field_test` shows `3`

Additionally, using the sort feature, by clicking the header of any column (not sure if multiple pages is a factor), appears to cause the expected `selected="selected"` behavior to be abandoned.

**Comment by johanneswilm** [comment]
Then morning, I tried it in a header of version 6, sorting that header and didn't notice anything.

I am no longer serving version 6 since version 7 was released. And now looking for that specifically, I don't see it in version 7 either. But I'd expect it to work the same.

Maybe you could make a jsfiddle example?

**Comment by rootlo0p** [comment]
Here is a jsfiddle example, which uses the @latest tagged version from jsdeliver CDN: [https://jsfiddle.net/wn50ueyb/](https://jsfiddle.net/wn50ueyb/)

There are only two rows/records, with 8 fields/columns in each. In the 8th field, a dropdown menu is present for each record.

Record 1's HTML source sets `selected="selected"` for option value `3` in field 8.
- On page load, the correct option value of `3` is shown/selected.
- On search, the option value automatically changes to the *incorrect* value of `1` (the first option value in the list)

Record 2's HTML source sets `selected="selected"` for option value `4` in field 8.
- On page load, the *incorrect* option value of `1` is shown/selected.
- On search, the option value automatically remains the *incorrect* value of `1` (the first option value in the list)

Thank you a ton for this project, by the way! If you have an established way for me to send you beer or food money, I'd love to!

**Comment by johanneswilm** [comment]
Hey @rootlo0p ,
thanks for that jsfiddle. Yes, indeed, it is currently not made for form fields in the table itself. A fix is possible, but it's something that will make the library slower for other uses. For that reason, I think the best is to make `form` an option in version 7.1.0. It will be turned off by default, as it does slow things down somewhat, but when turning it on it will be able to deal with form fields correctly.

Turning on `form` will probably be incompatible with some other options, such as "inline cell/row editing".

**Comment by johanneswilm** [comment]
Hey again @rootlo0p ,
If the user changes the selection and then subsequently searches or sort - what do you expect to happen with the value selected? Should it be reset to its initial value or keep the value selected by the user?

I am asking because that influences how these values should be handled. This could turn into quite a complex feature.

**Comment by rootlo0p** [comment]
Thank you for the updates! I think it's difficult to say how the search/sort would treat it, because it would be dependent on the server response. If the server accepts the change as valid, it would be desirable for the dropdown selection to remain as the user selected. If the server rejects the change, then the UI would be in a temporarily false reality until refreshed, unless the developer adds logic to adjust the DOM accordingly on rejection.

Switching to inline cell/row editing could be a good alternative. I didn't realize there was such a native feature in the framework. It may be slightly more laborious for the user than a dropdown, but I think it'd be a great compromise.

**Comment by johanneswilm** [comment]
@rootlo0p Yes, I think that would be the way to go. Currently inline editing is only about presenting a text input field, but we could expand that to allow for different input options so that your end users will not have to have a different experience.

I hope I will find some time for that soonish.

**Comment by ellinge** [comment]
Seems to be caused by the virtualdom diff? One has "empty" #text-nodes with '\n' while the other object compared is missing them.

**Comment by johanneswilm** [comment]
@rootlo0p The issue for this strange behavior was an internal mismatch between different diffing systems. That has been fixed in version 7.1.0. However - note that if a user actually makes an update to one of the selections, the table will not know about it and so it will potentially reset it when it is being sorted the next time. In order to make it aware of the change, the value in the cell representation of `datatable.data.data` needs to be updated. It is probably easier to make that column a column of just numbers and then use a `render` method to turn that number into a `<select>`.

**Comment by ellinge** [comment]
If one removed all whitespace (newlines) between the table-nodes it started working. When I looked on it it seems as if the diff is done between one table only having nodes and another one having empty "#text \n"-nodes. If they would have the same number of nodes then diff and the path (index to each node) probably would not be triggered. My guess is that the attribute is moved from the select to an empty #text-node based on the index path returned from the "action"-list in the diff.

**Comment by johanneswilm** [comment]
@ellinge You are right about the empty text nodes being present. Those are there initially because it reads the table from the HTML which often includes a lot of extra white space. But that was not the principal cause for this issue. Diffdom is actually stable enough that it can figure out removing text nodes, etc. without breaking.

The issue was this:

Diffdom offers two ways of handling dom nodes: A) It can either consider nodes that have different value than what they would have initially when loading the page, or B) it can ignore those values. B is faster, but A is needed if you want to diff forms that users have filled in already. The option is called `valueDiffing`: https://github.com/fiduswriter/diffDOM#disable-value-diff-detection

The issue was this: we had valueDiffing **disabled** when reading the initial dom (using `nodeToObj`), but **enabled** it when doing the actual diff process. That lead to these weird side consequences where it would add a `selected` attribute to an `<option>` but then think that the option should not actually be selected and unselect it.
