### ISSUE TITLE
Confusion about sorting a date column

### ISSUE THREAD

**Issue by silent-e** [fiduswriter/simple-datatables#252]
I can't seem to get date sorting to work correctly.  I've created a codepen with what I believe should be an extremely simple example.  I'm displaying a custom datetime format in the cell and specifying that it's a date in the `columns` config.  I've tried config in the JS.  I've tried adding the `data-` attributes on the `<th>`.  I've tried using a `format` option and nothing seems to work.  I've confirmed that dayjs does accurately parse my format without a need to specify the format but when sorting it always does it alphabetically instead of on the date data.  I've even tried adding the unix epoch timestamp in the `data-content` attribute on the cell but then that value actually gets written into the table cell when the javascript is initialized, which I think is a bug.

Any help is appreciated.  I'm trying to upgrade to v7

[Codepen is here](https://codepen.io/silent-e/pen/VwBVgLo)

matte

**Comment by johanneswilm** [comment]
OK, I'll take a look.

> I've even tried adding the unix epoch timestamp in the data-content attribute

Ddi you read about that in the documentation somewhere? If so, please let me so I can remove it. This is the way one did it in the old days. It's not working in current versions and shouldn't be available in the documentation anywhere.

**Comment by johanneswilm** [comment]
@silent-e It indeed seems to be an issue with your date strings.

If you start the data table like this:

```
window.datatable = new DataTable(...)
```

Then you can access the data in that table from the developer shell. like this:

```js
datatable.data.data
```
You'll see that each cell has an `order` attribute set to `NaN`. So that's an indication that dayjs couldn't figure out.

If I change your first string to `"September 7, 2022 14:01:33"` (removing an extra space + timezone) and change the format to `"MMMM D, YYYY H:mm:ss"` then it is indeed able to read it.

As far as I can tell, day.js doesn't have anything builtin to read PST/PDT. 

It may make sense to allow users to specify an order manually on the cell using something like a `data-order` attribute. Let me know if you talk to the day.js devs and what they recommend in terms of the timezone.

**Comment by johanneswilm** [comment]
@silent-e Try out 7.0.3. It allows you to add a `data-order` attribute to each cell to specify the order of that cell manually (just move and rename the `data-content` attributes you have in your example).

**Comment by silent-e** [comment]
Thanks for pointing out the date string issue.  I saw that dayjs doesn't process timezones.  It's weird but we'll have to deal with it.

I've confirmed that the data-order attribute is working perfectly.  Thanks for the fast turnaround!

(e)
