### ISSUE TITLE
Is there any plugin already created for Simple-DataTables?

### ISSUE THREAD

**Issue by juliorosseti** [fiduswriter/Simple-DataTables#31]
If yes, where can I find it?

grateful!

**Comment by johanneswilm** [comment]
Plugin - what kind of plugin are you thinking of @juliorosseti ?

**Comment by David-Carty** [comment]
One useful plugin, available in the original, is cell edit.  Does this feature in the ES2018 version?

**Comment by johanneswilm** [comment]
@David-Carty You mean this [1]? Simple-DataTables started out as a simple translation of VanillaDatatables, so by default all the same methods are available. So yes, also that editing plugin should work. See the wiki [2]. However, I don't use all aspects of this, so if it doesn't work, you need to report to. Before you open issues, please start out by checking the documentation and trying whether it works.

The one thing that doesn't work the same, due to the way ES2018 works, is that it needs to load external libraries explicitly. In Vanially DataTables it would simply look at the global name space and then behave differently if it noticed that the moments package was available.

[1] https://s.codepen.io/Mobius1/debug/rGpMMY

[2] https://github.com/fiduswriter/Simple-DataTables/wiki

**Comment by suhailkc** [comment]
@johanneswilm  How can I get/see the code of [1] [https://s.codepen.io/Mobius1/debug/rGpMMY](https://s.codepen.io/Mobius1/debug/rGpMMY) ??

**Comment by oneezy** [comment]
> @johanneswilm How can I get/see the code of [1] https://s.codepen.io/Mobius1/debug/rGpMMY ??

here you go https://codepen.io/Mobius1/pen/rGpMMY
