### ISSUE TITLE
¿How to contribute to the project?

### ISSUE THREAD

**Issue by DeniferSantiago** [fiduswriter/Simple-DataTables#35]
Greetings, there is some guide to start contributing, I am having the following problem when running "npm install".

"cp" is not recognized as an internal or external command,
program or executable batch file.

When you try to run the scripts found in the package.json:
```
"scripts": {
    "test": "npm run check_js",
    "check_js": "eslint src/",
    "compile": "npm run compile_js && npm run compile_js_umd && npm run compile_css && npm run compile_demo",
    "compile_js": "rollup -c",
    "compile_js_umd": "browserify dist/index.js --standalone simpleDatatables -o dist/umd/simple-datatables.js",
    "compile_css": "cp src/style.css dist/style.css",
    "compile_demo": "npm run compile_demo_js && cp node_modules/systemjs/dist/s.min.js demo/dist/nomodule/ && cp src/style.css demo/dist/style.css",
    "compile_demo_js": "rollup -c rollup.demo.config.js",
    "postcompile_demo": "cp -r dist/umd demo/dist",
    "prepare": "npm run compile"
  }
```

As I can solve that problem, I am new with npm and this is my first attempt to contribute.

When I try to pull, I get the following problem, why?
Maybe it has to do with what I have made the changes in master?

![githuberror](https://user-images.githubusercontent.com/41799285/63295165-feac4b80-c299-11e9-8b93-d8d7d22616aa.PNG)

**Comment by chrispelzer** [comment]
The `cp` command is for copy.
https://linux.die.net/man/1/cp

Are you running this on Windows OS?

**Comment by DeniferSantiago** [comment]
Yes, I use windows.  What would be the equivalent command in windows?

**Comment by johanneswilm** [comment]
@DeniferSantiago Hey, yes so this is mostly written with Linux and Mac OS X devs in mind because that's what I use and all other developers that have been working on this so far. I think there is an Ubuntu subsystem on Windows that can be activated somehow. That's probably the easiest way to get this working for you. But  you are also welcome to make a PR to add Windows support if that is possible (of course without disturbing the existing support for POSIX-compliant OSes).

**Comment by johanneswilm** [comment]
I will close this as your issue seems to be resolved. Please reopen if that is not the case.
