### ISSUE TITLE
Get DataTable object dynamically

### ISSUE THREAD

**Issue by BakiVernes** [fiduswriter/Simple-DataTables#38]
Let's say that i have 10+ datatables on my page.
I don't want to store them in a var but I want to get the datatable object dynamically.
How do I get the datatable object so i can use methods and options on it at a later time?

The documentation has examples like this:

`
let dataTable = new DataTable(myTable);

dataTable.on('datatable.XXXX', function(args) {
	// Do something when datatable.XXXX fires
});
`

I want to get something like this:

`dataTable.on('datatable.XXXX', function(args) {
	// Do something when datatable.XXXX fires
});`

Without creating a new datatable object.

**Comment by ebrensi** [comment]
@BakiVernes this issue is a few months old so I'm not sure if you figured it out but it appears you are getting the `DataTable` class mixed up with `dataTable`, which in your first example is an instance of `DataTable` that you created with `let dataTable = new DataTable(myTable);`.
You said
> I want to get something like this:

dataTable.on('datatable.XXXX', function(args) { // Do something when datatable.XXXX fires });

Without creating a new datatable object.

but `dataTable` _is_ a new `DataTable` object.

If you don't want to create a new `DataTable` object then it sounds like what you want is a class (static) method of the `DataTable` class.  Something like 
```
DataTable.on("click", e => console.log("you clicked"))
```
where you set a click handler to the whole `DataTable` class, so that it gets called when any instance of `DataTable` is clicked.   Class-level event-handlers are not possible as far as I know.

Does that help?
