### ISSUE TITLE
[BUG] data-order not working with negative numbers

### ISSUE THREAD

**Issue by Stoakes** [fiduswriter/simple-datatables#392]
- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this behavior is documented.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them handles this, but none of them did.

**Describe the bug**
Hello, thanks a lot for this library !

I think I found a bug : when setting the data-order attribute on cells and using negative values, the ordering doesn't work as expected.

**To Reproduce**

I have created this jsfiddle to demonstrate the issue : https://jsfiddle.net/6Lpjnqrk/

1. Go to https://jsfiddle.net/6Lpjnqrk/
2. Click on Variation header to sort the column (asc or desc, doesn't matter)
3. The rows are not ordered according to data-order value. Negative values are not taken into account. Even if it was sorted based on string value, that wouldn't look like that.

| Name   | Variation (ordered by asc) |
|--------|-----------|
| MSFT   | 0.0%      |
| FB     | 0.4%      |
| AAPL   | -0.5%     |
| PG     | -0.41%    |
| NVIDIA | 1.6%      |

**Expected behavior**
Values should be ordered according to data-order value :

| Name   | Variation (asc) |
|--------|-----------|
| AAPL   | -0.5%     |
| PG     | -0.41%    |
| MSFT   | 0.0%      |
| FB     | 0.4%      |
| NVIDIA | 1.6%      |

**Additional context**
This doesn't seem to be an issue related to floats. It behaves the same when using integers in data-order.

Have a good day

**Comment by johanneswilm** [comment]
@Stoakes The porblem is that if embed everything into the HTML, then how can the library be able to known that it should interpret the order-strings as numbers?  They are ordered correctly - if interpreted as strings, right? For better control, I'd put the data into JavaScript rather than the HTML.

If we still want to make this work, I guess we'd need to add another setting somewhere to make sure the library interpreted the order-strings as floats.

**Comment by Stoakes** [comment]
Thanks for taking care of this one so fast.

I confirm it's now working as intended with negative numbers.
