### ISSUE TITLE
[Feature request] Filter method

### ISSUE THREAD

**Issue by AndreasNorgaard** [fiduswriter/simple-datatables#399]
- [x] I have looked through the [documentation](https://fiduswriter.github.io/simple-datatables/documentation/) to try to see if this feature already exists.
- [x] I have looked at the [demos](https://fiduswriter.github.io/simple-datatables/demos/) to see if one of them does what I want, but none of them did.

**Is your feature request related to a problem? Please describe.**
The current implementation of table filters in simple-datatables allows for filtering based on predefined options, as demonstrated in this example: https://fiduswriter.github.io/simple-datatables/demos/10-filters/

The current approach uses the following configuration:
```javascript
columns: [
    {
        select: 1,
        filter: ["Assistant", "Manager"]
    },
]
```
While functional, this method doesn't provide the desired user experience for my application.

**Describe the solution you'd like**
I would like to implement a more flexible and user-friendly filtering system with the following features:
1. Dropdown Menu: Replace the current filter implementation with dropdown menus for each filterable column.
2. Multiselect Functionality: Allow users to select multiple options within each dropdown menu.
3. Dynamic Filtering: Implement a filter() method similar to the existing search() method.

This will require a new filter() method, which ideally would work as follows: 
```
dataTable.filter([
    {column: 1, values: ["Assistant", "Manager"]},
    {column: 3, values: ["New York", "Los Angeles", "Chicago"]}
]);
```

**Comment by johanneswilm** [comment]
@MartinBoge Guys, I am a regular web developer (also speaking Danish, btw) and I don't get any revenue from maintaining this library. I also have two small kids to worry about. So unless I need a feature myself, I don't usually just program features for others for free. If you want me to look at a PR, I am happy to do that, but otherwise, I think you should be prepared to wait up to a few years until I get around to looking at this. Maybe once my daughters leave for college in about 12-14 years or so I'll have more time.

**Comment by MartinBoge** [comment]
@johanneswilm apologies, it wasn't meant in a negative way. Was just curious in knowing what the state was - that's all :)

We're ready to negotiate if you have time to develop this for a price. Shoot me an email at martin.boge@live.dk if interested :)
