### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by MartijnHarmenzon** [fiduswriter/Simple-DataTables#6]
Can you please help me get started with Simple-Datatables? I used to have Vanilla-DataTables working fine, but I am having trouble here. Your help is much apreciated.

I am trying to use Simple-Datatables version 1.7.5.

I am using this to include the css:
`<link rel="stylesheet" href="node_modules/simple-datatables/dist/style.css">`

This to include the js:
`<script src="node_modules/simple-datatables/dist/index.js"></script>`

That will result in the following error:
> ReferenceError: exports is not defined
    at http://localhost:8080/www/dev/imviewer/node_modules/simple-datatables/dist/index.js:1:235

And if I use the following js code instead:
`import {DataTable} from "./node_modules/simple-datatables/dist/index.js"`

Then I will get the error:
> SyntaxError: The requested module './node_modules/simple-datatables/dist/index.js' does not provide an export named 'DataTable'

**Comment by MartijnHarmenzon** [comment]
I got it working by using the following:
`<script>
    var exports = {};
  </script>

  <script src="node_modules/simple-datatables/dist/index.js"></script>`

**Comment by johanneswilm** [comment]
Hey,
yes, so Vanilla-Datatables was written in pre-2015 type JavaScript. In 2015, with ES2015, all JavaScript started working quite differently. You'll want to follow the instructions in the README of this project, otherwise you'll almost certainly run into problems.

If you are still writing pre-2015 style JavaScript, it may make sense just to use the old Vanilla-Datatables until you update the entire stack to more modern type JavaScript with a bundler, etc. .

I am closing this as I assume it has been resolved. Please reopen if this is not the case.
