### ISSUE TITLE
Handle nested objects

### ISSUE THREAD

**Issue by MartijnHarmenzon** [fiduswriter/Simple-DataTables#68]
Is it possible to handle nested objects?

I created a simple example CodePen:
https://codepen.io/martijnharmenzon-the-looper/pen/qBbqNpv

The data is:
```
let data = [
    {
        prop1: "value1",
        prop2: {city: "London", country: "England"},
        prop3: "value3"
    },
    {
        prop1: "value4",
        prop2: {city: "Paris", country: "France"},
        prop3: "value6"
    }
];
```

As output I would like to make use of the object within 'prop2'. I am trying to use the render function.

Issue is that the data within the render function returns a string "[object Object]" and not a real object.

**Comment by ebrensi** [comment]
This issue is a few months old but I'll address it.  The way simple-datatables is implemented, every input value has to be a string.  The code that constructs a row from input data is in  `Rows.build`:
https://github.com/fiduswriter/Simple-DataTables/blob/688316f4f4603435290704d6e85f4c4d8133285b/src/rows.js#L20-L45

It creates a `td` element for each cell and puts your data in `innerHTML`, which only holds strings.  The render function later replaces that `innerHTML` however your render function transforms it.  It seems odd to me but that's how it works.

If you want to pass non-string data, the way it works now you'll have to convert each value you have to a string and process that string with your render function.

**Comment by johanneswilm** [comment]
Yes, so instead of using data directly, you'd do something like

```js
const reformedData = data.map(row => {
return [
    row.prop1,
    `${row.prop2.city}, ${row.prop2.country}`,
    row.prop3
  ]
})
```
