### ISSUE TITLE
Can I use it in my commercial app?

### ISSUE THREAD

**Issue by suhailkc** [fiduswriter/Simple-DataTables#69]
Is it legal to use this library in my commercial app?

**Comment by mdurajewski** [comment]
yes you can. But one important thing to take care of is that the GNU LGPL covered library is dynamically linked, not statically mixed with the main application.

Full info about lgpl in link below : http://answers.google.com/answers/threadview/id/439136.html

**Comment by johanneswilm** [comment]
Yes, so JavaScript is a bit odd as it doesn't entirely fit with how all these licenses were initially written. There are several interpretations out there on what exactly they mean, but the main point and the reason this license was chosen is that we want you to be able to use this library within your commercial, closed-source project without any problems and without having to open the source code of your app. If, however, you make bug fixes to the library code, the LGPL should make you commit those fixes back to this repository.

**Comment by amitjindal** [comment]
@johanneswilm May I ask a follow up question.

What if you are using this in a sveltejs or stencil application and you use:

`npm install simple-datatables`

And then import it as in the README:


```js
import {DataTable} from "simple-datatables"
const myTable = document.querySelector("#myTable");
const dataTable = new DataTable(myTable);
```

In this case the webpack bundler will be pulling the dist version of the JS into the webpack compiled JS script.

### Why am I asking this?

Because if you talk to a lawyer, they cannot really interpret it in the context. So I want to ask you and other owners of this code whether in your opinion this constitutes a LGPL violation or not.

I think the purpose and spirit of LGPL was to allow the usage but unfortunately it has brought the legal implications to avoid these licenses. I would love to use this in an application I am building. However its commercial and being a small company with very limited resources a good lawyer who can answer these is not a luxury I have.

Thanks
Amit

**Comment by johanneswilm** [comment]
In our eyes, this does not constitute a LGPL violation. If you want to, we can add some text specifying that in the README (please provide a PR for that if desired).

I don't really know why lawyers are going into overdrive about this. Yes, it's true that JavaScript and browsers make it slightly more complicated and the *GPL licenses were written in a different context and it would be good to have a more web-compatible version of the license, but the intention behind LGPL is still quite simple and easy to understand: Yes you can use this library in commercial, closed source applications. But yes, if you modify the sources of the library, then you need to send the modifications back. 

In the example you provide above, where you are directly importing from npm, you clearly have not modified the sources, so this is absolutely OK. If you ever do choose to modify the sources - well just sent the modifications to the Simple-DataTables sources back to us and you'll be OK. Your main app can stay being closed source.

**Comment by amitjindal** [comment]
@johanneswilm Sincerely thank you for clarification. I will try to write a section in README for this and submit a PR this weekend to help others understand this and be able to use this.
