### ISSUE TITLE
JSON: Only strings are shown

### ISSUE THREAD

**Issue by MartijnHarmenzon** [fiduswriter/Simple-DataTables#7]
Only strings are shown inside a datatable when importing from JSON.
How can I also get the numbers to be displayed?

I use the following JSON:
```
[
  {
      "Name": "Unity Pugh",
      "Ext.": 9958,
      "City": "Curicó",
      "Start Date": "2005/02/11",
      "Completion": "37%"
  },
  {
      "Name": "Theodore Duran",
      "Ext.": 8971,
      "City": "Dhanbad",
      "Start Date": "1999/04/07",
      "Completion": "97%"
  }
]
```

And the following js:
```
let dataTable = new DataTable(myTable, {
  ajax: {
    url: "someJSON.json",
  }
});
```

**Comment by johanneswilm** [comment]
Isn't that just the example data from the wiki [1] with the two numbers transformed from strings into numbers? If this is real data and a real issue you are having, can you not use the load functioned mentioned on that wiki page to transform those two numbers back into strings?

Please reopen if this doesn't work for you.
 
[1] https://github.com/fiduswriter/Simple-DataTables/wiki/ajax#example

**Comment by MartijnHarmenzon** [comment]
Thank you for the quick response. Yes, that's correct. It is the example. I used it to show the issue we are having with real data. But it also occurs with the example data. So why are the numbers of Ext. not shown when they are real numbers in the json data? Why are they only shown when the numbers are json coded as a string? So they are not shown like this: 9958, but they are shown like this: "9958". Hope you understand.

**Comment by MartijnHarmenzon** [comment]
Thanks for the quick response. Yes, that's correct. It is the example data to illustrate the issue we are having with our real data. Could you please explain why a number like 9958 is not shown and a number as a string "9958" is shown?

**Comment by johanneswilm** [comment]
Right. But as I said in my last response, there is a method to transform the data before using it. So there you transform it into a string. Typesafety is a good thing although in this case it's more coincidence.

**Comment by MartijnHarmenzon** [comment]
Ok. I understand. The load function might work, but because of the amount of data and the amount of numbers within the data it would not be our preferred way of doing it. It is also different from datatables.net. Therefore I would like to reopen this issue. I would also like to help or contribute if I would know how.

**Comment by johanneswilm** [comment]
The data conversion has to happen any way. There is no way you can make it faster by moving this code into Simple-DataTables, no matter how many numbers we are speaking of.

datatables.net is using what was common practice some 10 years ago when everything was relying upon jQuery. I assume that it automatically converts the data to a string. While that may seem convenient sometimes, it will quickly lead to all kind of problems when data is being auto converted like that. Read more about that for example [here](https://www.quora.com/What-is-type-safety-and-why-is-it-important).

So I don't think we should switch to the behavior of datatables. But what could be done is adding an example to the wiki of how to do the type conversion for such cases. Also note that in some cases you may want to just convert it to a string directly, whereas in other cases you may want to take into account the length of the number so that sorting works out correctly. Otheerwise "900" will be after "1000" just because "9" is larger than "1".

At least that is my initial take. Maybe there could be a way of specifying the type of each field, but there is no way it can involve fewer calculations than just converting all the data in the function as described above.
