### ISSUE TITLE
How to show export buttons?

### ISSUE THREAD

**Issue by StanMenten99** [fiduswriter/Simple-DataTables#73]
Hi,

How can I show the export buttons for csv, Excel and PDF?
Also: Can I add custom css classes?

Kind regards,
Stan,

**Comment by lamualfa** [comment]
You must create export button manually. Before that, make sure you have also installed [vanilla-datatables-exportable](https://github.com/Mobius1/Exportable) library to handle the export function because `export` method has been removed in `simple-datatables` version `2`. and for "*custom css classes*" question, until now `simple-datatables` does not support for this feature. I think it's normal because this library uses *GNU LGPL* for their license.

Why with the *GNU LGPL* license?

> But one important thing to take care of is that the GNU LGPL covered library is dynamically linked, not statically mixed with the main application.

See https://github.com/fiduswriter/Simple-DataTables/issues/69#issuecomment-653880014

**Comment by johanneswilm** [comment]
Actually, the license has nothing to do with any of these features.

**Comment by johanneswilm** [comment]
@lamualfa I needed to verify your claim - but no actually the export functions are still there https://github.com/fiduswriter/Simple-DataTables/blob/e0070b317ba797e9b36b224e37b1f560c8075af7/src/datatable.js#L1122

**Comment by johanneswilm** [comment]
And the export functions are actually not for csv, excel and PDF but rather csv, txt and sql.
