### ISSUE TITLE
clarification of sourcecode for contributors

### ISSUE THREAD

**Issue by ebrensi** [fiduswriter/Simple-DataTables#78]
I have been looking over the codebase trying to figure some stuff out.  I want to be able to create a table and add or remove data as needed.  I know that I could destroy and rebuild the table every time I change it but that would be inefficient.

I see that both `Rows.add` and `Table.insert` methods are supposed to add new rows of data, but one big problem with `Rows.add` is that it does not format cells using supplied render functions.  In order to do that, it would need to call `dataTable.setColumns`, which it doesn't.

I get the impression that @johanneswilm  had some plans for future development and abandoned them or got busy with other things.  Can you please give me an idea what direction you wanted to go with this?  I want to make contributions but trying to figure it all out from scratch is taking a while and there is not much documentation for developers.

**Comment by johanneswilm** [comment]
Hey @ebrensi ,
that's not really the case. We have one main product (fiduswriter) for which we needed a number of libraries to work. One of them was a datatable without jquery dependency, and so I decided to take on maintainership of this package when the previous maintainer had no more time to review pull requests. The libraries is doing what we need it to, for now, so there is no plan of adding new features on our part for now, and there really never was. We use it mainly to show a list of files. We will likely in the not too distant future add support for directories, so we need to represent a tree in some way and so that may trigger more needs.

However, we are open to review pull requests from other interested parties. Right now I see there are zero such requests waiting.

**Comment by johanneswilm** [comment]
Remember that I wasn't the original author. So I cannot tell "why" something is the way it is. What I can do is change it. If you want the process to be faster, you write a PR and I will review it. Removing things from the API usually requires increasing the major version.

**Comment by johanneswilm** [comment]
And have you looked at https://github.com/fiduswriter/Simple-DataTables/wiki ?

**Comment by ebrensi** [comment]
ok so you don't know why certain functions are deprecated, for example?
Somebody wanted them to not be there.

Unless I can find a better minimal data-table library I will have to work
with this one.  I need to be able to add or delete rows at will as
efficiently as possible and using as little memory as possible.  Thanks for
making it available.

**Comment by johanneswilm** [comment]
No, I don't know why that is. The previous maintainer will know though.
Feel free to propose sweeping changes that move the library in a new
direction. I'll do my best to help test new features and make sure that
existing functionality still works.

**Comment by ebrensi** [comment]
Haha yes.  And the code too.  The wiki is pretty vague about a lot of
things.  It suggests that `Rows.add` is more efficient than
`dataTable.insert` but it also appears to have a bug.  I don't want to make
any API-facing changes.  I just want the existing methods to work
correctly.  I'll submit a PR if I think I can improve anything.
